### ISSUE TITLE
[US-18] Print list of scannable QR codes from inventory

### ISSUE THREAD

**Issue by purplesmurf1998** [purplesmurf1998/Autotracks#101]
[[AP-52] As a user, I would like to print a list of QR codes for a list of selected vehicles in the dealership's inventory](https://soen390-team12.atlassian.net/browse/AP-52?atlOrigin=eyJpIjoiOGY5YzQxYzU0ZjI2NDU3ODgzNDQ4ODg3MzMxMTM5NDQiLCJwIjoiaiJ9)
This acceptance test should validate the following:
- Generate a PDF with the QR codes that were visible in the inventory at the time of the download.
- Let user decide how many QR codes per page
**This user story has been scoped out of the project and has not been implemented**

**Comment by coarchembault** [comment]
I approve the scoping out of this feature as it is not a necessity to print multiple QR codes at once and will not be used significantly.
