### ISSUE TITLE
US-19: Dashboard Informational Diagrams

### ISSUE THREAD

**Issue by TZnoj** [purplesmurf1998/Autotracks#117]
[AP-104](https://soen390-team12.atlassian.net/browse/AP-104) This acceptance test should validate the following:

That the diagrams are implemented
That the diagrams change when the input is changed (Monthly or Yearly sales)

Important to note that the diagrams are weirdly displayed during the test but do not display that way outside of the testing framework

**Comment by coarchembault** [comment]
Approved
