### ISSUE TITLE
Adding a vehicle with no vehicle properties will cause a dealership to not show any vehicles

### ISSUE THREAD

**Issue by TZnoj** [purplesmurf1998/Autotracks#41]
# Description
A dealership can have zero vehicle properties and add vehicles to its inventory. If vehicles are added, then the inventory won't be able to show any vehicles due to null values, but will show the vehicles from the previous dealership.
# Steps to Reproduce

1. Go to the "Create a new vehicle" page on a dealership with no vehicle properties set up
2. Create a new vehicle
3. Press "Yes" in the prompt
4. Go to the "Inventory" page and choose a dealership with vehicles.
5. Choose the dealership without vehicle properties
6. The user can click on the empty cells in the inventory to see an older vehicle
# Screenshots
![No properties](https://user-images.githubusercontent.com/28787145/146690111-aed81ab1-7280-4fa3-aaf5-a07ad50b119f.png)

![create vehicle](https://user-images.githubusercontent.com/28787145/146690113-e52ce7cd-78aa-4b8c-822c-e279b280d269.png)

![dealership view](https://user-images.githubusercontent.com/28787145/146690122-f6a82a54-02cf-4bb0-bdbc-4f95b312b3b6.png)

![erroneous vehicle](https://user-images.githubusercontent.com/28787145/146690124-63d9cba0-3d0a-4330-b4a9-dd927e791eb4.png)

# Priority
Low
# Related Jira Issue
[[AP-12] As a user, I would like to see the full list of vehicles in the dealership](https://soen390-team12.atlassian.net/browse/AP-12)

**Comment by purplesmurf1998** [comment]
Fixed by making the form visible and showing a warning in the InventoryAdd.vue file if no vehicle properties exist. For the inventory part, this was fixed by setting the tableItems to an empty array if `vehicleProperties.length` was 1.
