### ISSUE TITLE
Changing the values of a sale does not auto-refresh

### ISSUE THREAD

**Issue by TZnoj** [purplesmurf1998/Autotracks#53]
[AP-19](https://soen390-team12.atlassian.net/browse/AP-19?atlOrigin=eyJpIjoiMzAzZTI4NWFlOTVmNDFjYThiOWM4Yzc2ODk3YzZmMmQiLCJwIjoiaiJ9)
 As a user, I would like to assign sales representatives to deliveries, and mark vehicles as delivered.  

Description
When editing the values of a sale, the page does not auto refresh as it should.  

Steps to reproduce:  
- Start a sale on a vehicle and enter values for the sale
- Click on edit sale and change the values
- The values won't have changed but a banner appearing that says they have will appear

![image](https://user-images.githubusercontent.com/28787145/150895613-361b67a1-c287-44e0-95aa-c24baefeffb1.png)
![image](https://user-images.githubusercontent.com/28787145/150895646-103b385d-4560-454c-bef4-fade87307861.png)
![image](https://user-images.githubusercontent.com/28787145/150895683-57bc1449-8b58-45a8-891e-51d8f0b669c2.png)

**Comment by AbdulSir** [comment]
This issue has been addressed in the comment above
