### ISSUE TITLE
Bug when trying to edit transaction details

### ISSUE THREAD

**Issue by purplesmurf1998** [purplesmurf1998/Autotracks#54]
# Description
When trying to edit the transaction details for a specific vehicle, the vehicle is marked as delivered and the modal dissapears making it impossible to actually edit the details once the vehicle has been "delivered"
# Steps to reproduce

1. Create a new sale transaction from the vehicle details page
2. Navigate to the transactions table and select the created sale transaction
3. Click on the "Edit" button
4. The modal will disappear and the message shown in the screenshots will appear
# Priority
High - users must be able to change the details of a sale if needed.
# Screenshots
![image](https://user-images.githubusercontent.com/44242944/151013304-0ec53727-e390-4b74-ae5e-b9c61464640d.png)
![image](https://user-images.githubusercontent.com/44242944/151013397-c1f661dc-d53a-4d05-9e55-aed439e9c217.png)
![image](https://user-images.githubusercontent.com/44242944/151013454-76351051-095a-4929-a95c-5ed7bfa62e59.png)
# Jira Story
[[AP-19] As a user, I would like to assign sales representatives to deliveries, and mark vehicles as delivered](https://soen390-team12.atlassian.net/browse/AP-19?atlOrigin=eyJpIjoiNmZhMDg5ODU3YWU2NDBhNjhlMzQyZTM2NTE3MTE4ODMiLCJwIjoiaiJ9)

**Comment by AbdulSir** [comment]
This issue was addressed in the above commit. Closing this ticket
