### ISSUE TITLE
The comments counter does not get refreshed when a new comment is added, but it refreshes when a comment is deleted

### ISSUE THREAD

**Issue by AbdulSir** [purplesmurf1998/Autotracks#59]
User story: [AP-20](https://soen390-team12.atlassian.net/browse/AP-20?atlOrigin=eyJpIjoiODA3ZDUzYTAyMWM5NDU0MDg4NzUzNmY3NWYxYmYzYjYiLCJwIjoiaiJ9) As a user, I would like to comment on vehicles in the dealership

Description:
When a new comment is added the comments counter does not get incremented. However, when a comment is deleted it gets decremented.

Steps to reproduce:

- Go to a vehicle detail page
- Click 'Write a comment'
- Write a comment and post it
- The comment counter section should increment but it does not
- Delete that comment. The comments counter gets decremented

![image](https://user-images.githubusercontent.com/44450682/151279917-7a1e2d5d-63ab-4048-963b-50d1bfedca12.png)
![image](https://user-images.githubusercontent.com/44450682/151279973-0237ef3e-c7c7-4005-88aa-1111a79c32a1.png)
![image](https://user-images.githubusercontent.com/44450682/151280028-079b07d5-b51a-44b9-a8b4-37c731711793.png)
![image](https://user-images.githubusercontent.com/44450682/151280070-0b7c7813-dd13-46ce-b5d1-82d9cbce1a25.png)
![image](https://user-images.githubusercontent.com/44450682/151280087-1ab4f611-84dc-4f2b-8f0a-0771aedb2722.png)

**Comment by purplesmurf1998** [comment]
This bug was fixed in this [commit](https://github.com/purplesmurf1998/Autotracks/commit/968a62eead92386336bf258257fbb7ac9e631feb)

Simply needed to increase counter after posting the comment.
