### ISSUE TITLE
US-10 Adding Vehicles to Inventory

### ISSUE THREAD

**Issue by TZnoj** [purplesmurf1998/Autotracks#67]
[AP-13](https://soen390-team12.atlassian.net/browse/AP-13) This acceptance test should validate the following:
- Every vehicle property listed to the dealership should appear
- Specify in which dealership the vehicle is getting added to (if logged in as admin and have multiple dealerships)
- Required vehicle properties must validate properly
- Prompt to add another vehicle after creation. If not, redirect to the inventory

**Comment by coarchembault** [comment]
Passed
