### ISSUE TITLE
US-13 Assigning Salesperson to Vehicle and Making a Sale

### ISSUE THREAD

**Issue by TZnoj** [purplesmurf1998/Autotracks#70]
[AP-18] (https://soen390-team12.atlassian.net/browse/AP-18) This acceptance test should validate the following:
- Able to see who is assigned to a vehicle
- Able to assign someone to a vehicle
- Able to make a pending sale
- Management or administration needs to accept “sale” on their account before it can be finalized

**Comment by coarchembault** [comment]
Passed
