### ISSUE TITLE
US-16 Edit Properties of Vehicles of a Dealership

### ISSUE THREAD

**Issue by TZnoj** [purplesmurf1998/Autotracks#73]
[AP-39](https://soen390-team12.atlassian.net/browse/AP-39) This acceptance test should validate the following:

- Vehicles added after the modification will have the new template
- Must be able to edit a property template linked to a dealership

**Comment by coarchembault** [comment]
Passed

**Comment by AbdulSir** [comment]
@TZnoj @purplesmurf1998 Would you guys know why the PO did not comment on this acceptance test yet?

**Comment by coarchembault** [comment]
I approve this acceptance test
