### ISSUE TITLE
Snapshot Testing is giving error

### ISSUE THREAD

**Issue by AbdulSir** [purplesmurf1998/Autotracks#78]
# Description
Once I try to run npm run snaptest on the frontend, I get an error.

# Steps to Reproduce

- Navigate to the frontend directory
- run `npm run snaptest -- -u`
- the tests will run and give an error at the end
# Priority
Low
# Screenshots
![image](https://user-images.githubusercontent.com/44450682/151709281-7bc20a97-a9dc-4254-9c4c-8ed245ff729e.png)

![image](https://user-images.githubusercontent.com/44450682/151709290-81cd8de6-df13-4a7c-a818-4fe5e5e278b4.png)

**Comment by AnthonyChraim** [comment]
I am currently unable to replicate the bug. This might be an issue with dependencies. I will look further into it next sprint and see if the bug persists when we are all running in the same environment with Docker.

**Comment by AbdulSir** [comment]
@AnthonyChraim any updates on this?

**Comment by AnthonyChraim** [comment]
I modified the erroneous tests and removed some of the unnecessary ones. There are still some bugs to resolve but it is coming along nicely. I will also be adding additional snapshot tests for the new components.

**Comment by Emperor42** [comment]
Jenkins is now setup where it will run the tests but the test failing will not cause the build to fail. We can setup a threshold percentage where we would fail the build if we are below that amount of passed tests

**Comment by AnthonyChraim** [comment]
Problematic snapshots were fixed, snapshots that were out of the scope of our project were removed, new relevant snapshots were added
