### ISSUE TITLE
404 Page error when trying to add a vehicle without selecting a dealership

### ISSUE THREAD

**Issue by AbdulSir** [purplesmurf1998/Autotracks#80]
[AP-13](https://soen390-team12.atlassian.net/browse/AP-13?atlOrigin=eyJpIjoiMmYwNzlkM2Y2NDMyNDFmZGJkNjdkZmQyZDdmNTY1OTciLCJwIjoiaiJ9) As a user, I would like to add vehicles to the dealership's inventory

A 404 page error was rendered when the app was being tested as part of the usability testing phase.

### Steps to Reproduce:

- Create a dealership
- Create a vehicle property
- Navigate to the inventory to add a vehicle
- Click on Add vehicle to inventory (without selecting the dealership first)
- a 404 page is rendered

### Screenshots:

Dealership Created:
![image](https://user-images.githubusercontent.com/44450682/151713359-9df084b5-a95b-46f9-b981-1a4e7f3ead18.png)

Navigate to the inventory page:
**Do not select a dealership!**
![image](https://user-images.githubusercontent.com/44450682/151713380-037344d1-035c-4579-a8a3-9bb0e879cf2d.png)

Click on add vehicle(s) to the inventory:
![image](https://user-images.githubusercontent.com/44450682/151713392-e2123bb1-71f4-4a51-a02d-60a8b16e8935.png)

404 page is rendered:
![image](https://user-images.githubusercontent.com/44450682/151713400-0ed2c317-3f13-4036-b2b7-d4f4457dea6a.png)

**Comment by purplesmurf1998** [comment]
Issue fixed in the following [commit](https://github.com/purplesmurf1998/Autotracks/commit/79df1d02b5bee8f180a34c56b7abb90e4bfcd6f3)
