### ISSUE TITLE
Vehicle delivery status not saving

### ISSUE THREAD

**Issue by AnthonyChraim** [purplesmurf1998/Autotracks#81]
[AP-19](https://soen390-team12.atlassian.net/browse/AP-19) As a sales rep, I would like to create a sale and assign a manager to approve. As a manager, I would like to approve/edit sale. As a user, I would like to mark vehicle as delivered.

After marking the vehicle as delivered, the vehicle's status stays as not delivered after closing the window.

### Steps to Reproduce:

-Create a vehicle
-Sell the vehicle
-Approve the sale
-Mark the vehicle as delivered
-Close window
-Open window again
-Vehicle's status will show as "not delivered"

### Screenshots:
Mark vehicle as delivered:
![image](https://user-images.githubusercontent.com/42822998/151714405-dcb7f06d-59f1-482d-a252-cec8cb93fef4.png)

Vehicle appears to be delivered:
![image](https://user-images.githubusercontent.com/42822998/151714434-af143c7a-1729-40cd-a920-68ceeaea70fc.png)

Vehicle appears as not delivered after closing and opening the window:
![image](https://user-images.githubusercontent.com/42822998/151714457-e260612a-2a21-4f5d-9169-fb22d1c28837.png)

**Comment by purplesmurf1998** [comment]
I'd comment that marking the vehicle delivered through the transaction modal works fine. Only from the dropdown it doesn't seem to be saving but only changing the frontend value.

**Comment by purplesmurf1998** [comment]
Fixed in the following [commit](https://github.com/purplesmurf1998/Autotracks/commit/e369dffdabf3320c3b6fa62cd9001c09893127fe)
