### ISSUE TITLE
US-17 Subscribe to Events and Receive Alerts

### ISSUE THREAD

**Issue by purplesmurf1998** [purplesmurf1998/Autotracks#82]
[[AP-29]](https://soen390-team12.atlassian.net/browse/AP-29?atlOrigin=eyJpIjoiY2ZiYzM2NTRmYTI1NDZhZDhjY2VmNGYwOTBlYTA5NjMiLCJwIjoiaiJ9) This acceptance test should validate the following:

- As a user, I would like to select events to receive notifications on
- I would like to receive notification when a vehicle is:

1. deleted
2. marked missing/found
3. marked delivered
4. pending approval for sale
5. approved
6. sale transaction is modified

**Comment by coarchembault** [comment]
Failed

I can see that notifications work, however I cannot subscribe to specific event types and modify my subscriptions.

**Comment by AbdulSir** [comment]
This will be addressed in next sprint.

**Comment by coarchembault** [comment]
Passed
